version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql     
    networks:
      - fullstack
  mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_USER=go-live
      - MYSQL_PASSWORD=go-live
      - MYSQL_DATABASE=go-live
      - MYSQL_ROOT_PASSWORD=go-live
    
    networks:
      - fullstack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge